[book]
authors = ["heather Baier", "Steve Morse", "James Elmore"]
language = "en"
text-direction = "ltr"
multilingual = false
src = "src"
title = "Distributed ML @ W&M"
description = "A guide to using the HPC at W&M for distributed machine learning."

[build]
build-dir = "book"
create-missing = false
